---

test:
  fengyun3_home: /software/fengyun
  ld_library_path: /software/fengyun/fy3dl1db/lib

  listen_topic: /XLBANDANTENNA/FENGYUN3D/CLEAR

  #Not needed, used to limit number of modules to listen to
  listen_service: move_it_CLEAR-FENGYUN3D

  #If not given, default is used as publish topic
  publish_topic: /XLBANDANTENNA/FENGYUN3D/L1B

  #If not given /tmp is used
  working_dir: /data/pytroll/fengyun3/working_dir

  #The file name format of the data. This match the one used in the satpy mersi reader.
  fy3_l0: 'tf{start_time:%Y%j%H%M%S}.{mission}-X'

  #Instrument/sensors to process to l0 in order
  process_instrument_scripts_l0:
    - Fy3VassL0db.csh
    - Fy3MersiL0db.csh
    - Fy3HirasL0db.csh

  #Instrument/sensor to process to l1 in order
  process_instrument_scripts_l1:
    - Fy3MersiL1db.csh
    - Fy3HirasL1db.csh
    - Fy3MwhsL1db.csh
    - Fy3MwtsL1db.csh
    #Note: MWRI only available for FY3ABC
    - Fy3MwriL1db.csh

  #Where to check for the leapsec and utcpole files
  leapsec_utcpole: https://oceandata.sci.gsfc.nasa.gov/Ancillary/LUTs/modis/

  #Where to look for the 1le files and where to store them
  one_le:
    - {http: http://file.nsmc.org.cn/ONELINE/FY3D/43010.dat, out: /software/fengyun/fy3dl1db/SysData/fy3d1line.dat}
#    - {http: http://file.nsmc.org.cn/ONELINE/FY3C/39260.dat, out: /software/fengyun/fy3dl1db/SysData/fy3c1line.dat}
